### ISSUE TITLE
getTEvents: why abs() in diff = np.log(gRaw).diff().dropna().abs()?

### ISSUE THREAD

**Issue by WongYatChun** [BlackArbsCEO/Adv_Fin_ML_Exercises#14]
Hi, I am new to this community.

I find your `getTEvents` function in _`Labeling and MetaLabeling`_ is different from the code provided by the author (code snippets [2.5.2.1]).

`np.log(gRaw).diff().dropna().`

I understand you would like to convert the prices into returns, and then compare the cumulative returns with the volatility threshold.

but why adding .abs() at the end?
You turn all the negative returns to positive returns, but I cannot understand the logic behind.

Can you explain your rationale?

Thanks

**Comment by BlackArbsCEO** [comment]
typo. thanks for the correction, fixed in 977a92b83ded86171a73bea6e1bd73d5c48f2d3b

**Comment by coco90417** [comment]
hi I am new to this, I am wondering what is the reason behind using np.log(gRaw).diff().dropna() to calculate cumulative returns, instead of np.exp(np.log(gRaw).diff()) -1).dropna()? seems that we would need to exponentiate the logged price difference and subtract by 1 to recover the return.
