### ISSUE TITLE
sys.path is being populated with all directories and files below src

### ISSUE THREAD

**Issue by ianxtreem** [BlackArbsCEO/Adv_Fin_ML_Exercises#17]
Not a huge deal, but in Tick, Volume, Dollar Bars.ipynb the sys.path is being populated with every file and directory under /src instead of just the directories as I think is intended.  
```python
script_dirs = list(Path(script_dir).glob('./*/'))
for sdir in script_dirs: 
    sys.path.append(sdir.as_posix())
```
Suggest replacing with the snippet below for just the directories
```python
for (_, script_dir, _) in os.walk('./src'):
    sys.path.append(script_dir)
```
Thanks for starting this project.  I am behind you and the others in my studying and implementation but I hope to catch up and contribute.

**Comment by BlackArbsCEO** [comment]
Thanks for pointing this out. I updated the older notebooks to import from `src` correctly instead of the `sys.path.append` method. See a7e4b4b43be5071e537b98ce5edcf2e0b7a29e10
