### ISSUE TITLE
Ch3 Notebook: Adjust the getBins function

### ISSUE THREAD

**Issue by Jackal08** [BlackArbsCEO/Adv_Fin_ML_Exercises#22]
Question 3.3, pg 55: Adjust the getBins function (Snippet 3.5) to return a 0 whenever the vertical barrier is the one touched first.

We need to correct this line of code in the get_bins function.
```out['bin']=np.sign(out['ret'])```

**Comment by BlackArbsCEO** [comment]
thanks for the heads up, check out the updated notebooks. fixed dd47196ae766c385b4a6ffe1519c39c89b740851
