### ISSUE TITLE
Question about applyPtSlOnT1

### ISSUE THREAD

**Issue by ivan-vasilev** [BlackArbsCEO/Adv_Fin_ML_Exercises#4]
In the method [3.2] applyPtSlOnT1, there is:

`        df0=(df0/close[loc]-1)*events_.at[loc,'side'] # path returns
`

This line is the same as in the book, however what is the point of multiplying the returns by the predicted side: `*events_.at[loc,'side']`? Wouldn't this change the sign of the returns and thus create an error when the barriers are computed on the next line? I know this is not a bug, so I'm sorry about asking here.

**Comment by Chetanbuye12** [comment]
what is the column "side" about ?
Does it represent long as 1, short as -1 ????

**Comment by ivan-vasilev** [comment]
Yes, this is my understanding. Side represents long as 1 and short as -1. The side parameter is the prediction of the first step of the algorithm. It is used in the meta-labeling part (second step). However, I don't understand why it's necessary to multiply by it.

**Comment by BlackArbsCEO** [comment]
@ivan-vasilev a positive return is only beneficial if you're long. If you're short it's a negative outcome. The reverse is also true, a negative return is only beneficial if you're short. If you're long it's a negative outcome. The side is a binary variable indicating whether you are long or short.

Example:
```
Long positions:
+1% * 1 (side) = +1% (good)
-1% * 1 (side) = -1% (bad)

Short positions:
+1% * -1 (side) = -1% (bad)
-1% * -1 (side) = +1% (good)
```
