### ISSUE TITLE
Potential bug in PurkedKFold class 

### ISSUE THREAD

**Issue by agalbachicar** [BlackArbsCEO/Adv_Fin_ML_Exercises#43]
The following notebook:

```
Adv_Fin_ML_Exercises/notebooks/07. Cross Validation in Finance.ipynb
```

Where it says:

```python
maxT1Idx=self.t1.index.searchsorted(self.t1[test_indices].max())
```

I believe it should be:

```python
maxT1Idx=self.t1.index.searchsorted(self.t1.index[test_indices].max())
```

Note that the book states exactly the same as you proposed, however, I think it should be as I propose.

**Comment by BlackArbsCEO** [comment]
Hey thanks for the insight. I recommend you post this on the mlfinlab github as they have created a coherent python module that implements all the concepts in the book.

**Comment by agalbachicar** [comment]
Closing this one. Will check the code of https://github.com/hudson-and-thames/mlfinlab/blob/3c80f269bc68b8cb9bcf863ceb3dc77fc14b6984/mlfinlab/cross_validation/cross_validation.py and create a ticket there if it applies. Thanks!
