### ISSUE TITLE
Issue with "getDailyVol" function

### ISSUE THREAD

**Issue by Chetanbuye12** [BlackArbsCEO/Adv_Fin_ML_Exercises#5]

**Comment by BattlestarPegasus** [comment]
You need to drop any duplicates in your DataFrame's index.  For example, after I generated volume bars, i need to check if there are any duplicates in my index.  I found this to be an issue when working with raw trade data.  I do not have this issue with re-sampled closed bars in the 1min or above.

`temp = len(v_bar_df)
v_bar_df = v_bar_df[~v_bar_df.index.duplicated(keep='first')]
print('Duplicates Droped from volumebars | '+str(len(v_bar_df)-temp))`
