### ISSUE TITLE
where the top data directory?

### ISSUE THREAD

**Issue by wuyunhua** [BlackArbsCEO/Adv_Fin_ML_Exercises#8]
did you missing top "data" directory?
and after executing 'python ../src/data/make_dataset.py', it just only print "2018-09-04 13:35:22,438 - __main__ - INFO - making final data set from raw data" and no data generating...

**Comment by BlackArbsCEO** [comment]
The top data directory is meant to be created on your local machine. To summarize, when I create a new github project repo I use the following resource: [driven data cookiecutter templates](https://github.com/drivendata/cookiecutter-data-science). This template produces "empty" files in some of the directories to guide the developer's use of the template. 

If you want the dataset used in the project go to my [blog](http://www.blackarbs.com/blog/labeling-and-meta-labeling-returns-for-ml-prediction) and in the *Links* section it has the download link for the data in `parquet` format.

**Comment by beyondguo** [comment]
> The top data directory is meant to be created on your local machine. To summarize, when I create a new github project repo I use the following resource: [driven data cookiecutter templates](https://github.com/drivendata/cookiecutter-data-science). This template produces "empty" files in some of the directories to guide the developer's use of the template.
> 
> If you want the dataset used in the project go to my [blog](http://www.blackarbs.com/blog/labeling-and-meta-labeling-returns-for-ml-prediction) and in the _Links_ section it has the download link for the data in `parquet` format.

Hi, would you please share the download link again?  The kibot link and your provided link seem to have expired.  Thanks a lot!
